### ISSUE TITLE
[BUG] Fix CustomFont

### ISSUE THREAD

**Issue by LachCrafter** [3arthh4ckDevelopment/3arthh4ck-Fabric#57]
**Describe the bug**  

**To Reproduce**  
1. Install arch linux.

**Expected behavior**  
The fonts wont load and it will load a random one.

**Crashlog**  
No errors.

**Additional context**  

![image](https://github.com/3arthh4ckDevelopment/3arthh4ck-Fabric/assets/100131971/b89bc1c1-3cf8-45ef-99c5-4704e29d0e51)

**Comment by nukiz** [comment]
fixed in https://github.com/3arthh4ckDevelopment/3arthh4ck-Fabric/commit/24da6ea33b16ddabb2d38c3abe532930019bc183?

**Comment by LachCrafter** [comment]
still happening
![image](https://github.com/3arthh4ckDevelopment/3arthh4ck-Fabric/assets/100131971/a483f001-0aaf-4036-8667-eb2d39f189b0)

**Comment by LachCrafter** [comment]
and yes i have the fonts installed on my system

**Comment by LachCrafter** [comment]
The directories in linux for the fonts are mostly
home/<username>/.local/share/fonts (or ~/.local/share/fonts to be quick).
There will be folders with each font file.
like that:

├── CascadiaCove
│   ├── Caskaydia Cove Nerd Font Complete Mono Regular.otf
│   └── Caskaydia Cove Nerd Font Complete Regular.otf
├── JetBrains
│   └── JetBrains-Mono-Nerd-Font-Complete.ttf

etc.

**Comment by nukiz** [comment]
ok might fix it soon

**Comment by nukiz** [comment]
fixed in https://github.com/3arthh4ckDevelopment/3arthh4ck-Fabric/commit/397e244568a782de0690d16a4f4214e55ed8c697?
